services:
  # Development overrides for backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      # Development environment variables
      GIN_MODE: debug
      LOG_LEVEL: debug
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      - /app/bin  # Exclude binary directory
    command: >
      sh -c "
        echo 'Starting development server with hot reload...' &&
        go mod download &&
        go install github.com/air-verse/air@latest &&
        air -c .air.toml
      "
    stdin_open: true
    tty: true

  # Development database with different settings
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: restaurant_platform_dev
    ports:
      - "5433:5432"  # Different port for dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

  # Redis with different port for dev
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Different port for dev
    volumes:
      - redis_dev_data:/data


volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local