version: '3.8'

services:
  # === INFRASTRUCTURE ===
  
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: restaurant-postgres
    environment:
      POSTGRES_DB: restaurant_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurant_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis Cache & Message Broker
  redis:
    image: redis:7-alpine
    container_name: restaurant-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    command: redis-server --appendonly yes

  # === BACKEND SERVICES ===
  
  # Menu Service
  menu-service:
    build:
      context: ./backend/menu-service
      dockerfile: Dockerfile
    container_name: restaurant-menu-service
    ports:
      - "8081:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_NAME: restaurant_platform
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Order Service
  order-service:
    build:
      context: ./backend/order-service
      dockerfile: Dockerfile
    container_name: restaurant-order-service
    ports:
      - "8082:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_NAME: restaurant_platform
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Kitchen Service
  kitchen-service:
    build:
      context: ./backend/kitchen-service
      dockerfile: Dockerfile
    container_name: restaurant-kitchen-service
    ports:
      - "8083:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_NAME: restaurant_platform
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Reservation Service
  reservation-service:
    build:
      context: ./backend/reservation-service
      dockerfile: Dockerfile
    container_name: restaurant-reservation-service
    ports:
      - "8084:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_NAME: restaurant_platform
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Inventory Service
  inventory-service:
    build:
      context: ./backend/inventory-service
      dockerfile: Dockerfile
    container_name: restaurant-inventory-service
    ports:
      - "8085:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres123
      DB_NAME: restaurant_platform
      DB_SSLMODE: disable
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      GIN_MODE: debug
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # === API GATEWAY ===
  
  api-gateway:
    image: nginx:alpine
    container_name: restaurant-gateway
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      menu-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
      kitchen-service:
        condition: service_healthy
      reservation-service:
        condition: service_healthy
      inventory-service:
        condition: service_healthy
    networks:
      - restaurant-network
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  restaurant-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16