version: '3.8'

services:
  # k6 runner service
  k6:
    image: grafana/k6:latest
    networks:
      - restaurant-network
    volumes:
      - ./scripts:/scripts
      - ./scenarios:/scenarios
      - ./lib:/lib
      - ./results:/results
    environment:
      - BASE_URL=http://backend:8080
    command: run /scripts/menu-service.js
    depends_on:
      - backend

  # InfluxDB for storing k6 metrics
  influxdb:
    image: influxdb:1.8
    networks:
      - restaurant-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - influxdb-data:/var/lib/influxdb

  # Grafana for visualizing k6 metrics
  grafana:
    image: grafana/grafana:latest
    networks:
      - restaurant-network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb

  # Backend service (placeholder - replace with your actual backend)
  backend:
    build:
      context: ../../
      dockerfile: Dockerfile
    networks:
      - restaurant-network
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=restaurant_platform
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    networks:
      - restaurant-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restaurant_platform
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  influxdb-data:
  grafana-data:
  postgres-data: