version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - perf-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - perf-network

  # Backend Service
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: restaurant_platform
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/menus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - perf-network

  # InfluxDB for k6 metrics
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - perf-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - influxdb
    networks:
      - perf-network

  # k6 test runner - runs once and exits
  k6:
    image: grafana/k6:latest
    command: >
      run
      --out influxdb=http://influxdb:8086/k6
      --no-usage-report
      /tests/${TEST_SCRIPT:-scripts/menu-service.js}
    environment:
      BASE_URL: http://backend:8080
      K6_INFLUXDB_INSECURE_SKIP_TLS_VERIFY: "true"
    volumes:
      - ./scripts:/tests/scripts:ro
      - ./scenarios:/tests/scenarios:ro
      - ./lib:/tests/lib:ro
      - ./results:/tests/results
    depends_on:
      backend:
        condition: service_healthy
      influxdb:
        condition: service_started
    networks:
      - perf-network

networks:
  perf-network:
    driver: bridge

volumes:
  postgres-data:
  influxdb-data:
  grafana-data: